### ISSUE TITLE
hls.js 0.13.2 update

### ISSUE THREAD

**Issue by EarlThorfinn** [streamroot/videojs-hlsjs-plugin#104]
Hi,

hls.js 0.13.2 has been released (https://github.com/video-dev/hls.js/releases/tag/v0.13.2) and includes a bugfix I'm keen to test for my use case.

To update videojs-hlsjs-plugin to use hls.js 0.13.2 rather than 0.12.4, can you please advise if it is simply a case of updating the dependency in package.json and re-running `npm install` and `npm run build`?

Or are there likely to be compatibility considerations?

Thanks

**Comment by tri170391** [comment]
If there's nothing change public API or player events-wise then it would be fine to just bump the dependency version in `package.json`. TBH you can also remove the deps and change the instantiation of Hls class to read from `<script src=...>`loaded `hls.js` if it fits better for your use case.

**Comment by EarlThorfinn** [comment]
Many thanks for the speedy reply @tri170391. I bumped the version in package.json, rebuilt the dist script, and have pushed to my production. So far so good!
