### ISSUE TITLE
Force player to play latest content

### ISSUE THREAD

**Issue by ipepe** [streamroot/videojs-hlsjs-plugin#108]
Hey. I'm working on my private streaming server and I noticed that I have delay on my player (+20 seconds). I changed config in my nginx but that did help only a little. I noticed that I can set `player.playbackRate(2)` and that will move player forward and reduce delay to something around 9-10 seconds which is great. But playback is unwatchable with that speed and it's buffering and waiting every few seconds. Is there an option to force player into playing only latest content? Especially if someone pauses for a second or two. Basically an ability to move playback forward on demand/automatically if delay is longer than 20 seconds?

**Comment by tri170391** [comment]
I guess you can use `hls.js` `config.hlsLiveMaxLatencyDuration` or `config.hlsLiveMaxLatencyDurationCount` for this.

**Ref:** https://github.com/video-dev/hls.js/blob/master/docs/API.md#livemaxlatencydurationcount

**Comment by ipepe** [comment]
This seems like an option that should work. But I can't get it to "skip forward" I even set counts quite low and still didn't notice enforcing of these values:
```json
{ liveSyncDurationCount: 1, liveMaxLatencyDurationCount: 3 }
```

**Comment by tri170391** [comment]
Can you forward the problem to `hls.js` team. Also by using count it is a multiple of your segment duration, it could means 10s and 30s if your segment size is 10s.

**Comment by ipepe** [comment]
I confirmed that configuration is properly set up with:
```js
        videojs.Html5Hlsjs.addHook('beforeinitialize', (videojsPlayer, hlsjsInstance) => {
            debugger
        });
```

Could You help me find out what is my segment size and we can close this issue?

**Comment by tri170391** [comment]
You can check the `level HLS manifest`, there should be a `#EXT-X-TARGETDURATION`

**Comment by ipepe** [comment]
Ok. That seems to equal 4. I will experiment with it more and see how it works in practice.
