### ISSUE TITLE
How to modify options of a http request?

### ISSUE THREAD

**Issue by sethurv** [streamroot/videojs-hlsjs-plugin#109]
`videojs.Hls.xhr.beforeRequest` can be used to parse a http request. Where the handler is not invoked when the plugin is used. Let me know how this can be achieved.

**Comment by tri170391** [comment]
You can do that with `Hls.js` equivalent: https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup

You can set config for the `Hls.js` instance via: https://github.com/streamroot/videojs-hlsjs-plugin#passing-configuration-options-to-hlsjs

**Comment by sethurv** [comment]
I could make use of `xhrsetup` function to modify the http request. Thanks!
