### ISSUE TITLE
missing timeupdate event and progress event while autoplay

### ISSUE THREAD

**Issue by dioramayuanito** [streamroot/videojs-hlsjs-plugin#110]
i'm using videojs-hlsjs-plugin v1.0.13 and i found that if we make player as autoplay, then timeupdate event and progress event are missing

**Comment by tri170391** [comment]
According to `video.js` documentation `progress` is not a player-level event.

For the `timeupdate` event it works fine on my side:
![image](https://user-images.githubusercontent.com/1035705/97970175-6a0c0b80-1dc1-11eb-94ec-0b07d68e3882.png)

**Comment by dioramayuanito** [comment]
thanks alot for your fast response mr Nguyen. i'll recheck my code again ... 👍👍👍

**Comment by blacktrash** [comment]
https://docs.videojs.com/player#event:progress ?
The event also fires for me[tm]. What am I missing?

**Comment by dioramayuanito** [comment]
i found that videojs-contrib-ads somehow block timeupdate event, progress event, and ended event of hls.js.
i'll report to videojs-contrib-ads
