### ISSUE TITLE
HLS.js 1.4.x breaks hls.js instance

### ISSUE THREAD

**Issue by dioramayuanito** [streamroot/videojs-hlsjs-plugin#117]
we found that HLS.js 1.4.x makes everything messed up inside videojs-hlsjs-plugin.js. HLS.js upgrade their packager to a new one.

**Comment by phloxic** [comment]
This works for me[tm]:
```js
--- a/lib/videojs-hlsjs-plugin.js
+++ b/lib/videojs-hlsjs-plugin.js
@@ -1,4 +1,4 @@
-var Hlsjs = require('hls.js');
+var Hlsjs = require('hls.js/dist/hls.js');

 var registerSourceHandler = function (videojs) {
     var hooks = {};
diff --git a/package.json b/package.json
index a1b4fdb..87e5042 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "test:lint": "eslint lib/"
   },
   "dependencies": {
-    "hls.js": "0.13.2"
+    "hls.js": "1.4.12"
   },
   "devDependencies": {
     "ajv": "^6.4.0",
```
See https://github.com/video-dev/hls.js/issues/5288#issuecomment-1675040141

I then avoid build failure with:
```sh
env NODE_OPTIONS=--openssl-legacy-provider npm run build
```
There's probably a more elegant solution for that.

**Comment by dioramayuanito** [comment]
thank you very much sir @phloxic

**Comment by phloxic** [comment]
@dioramayuanito - depending on your setup you may also want to load/configure [hls.worker.js](https://github.com/video-dev/hls.js/blob/46a7ca29bec3453bf39bc9919aba5ce189d17895/docs/API.md#workerpath)

**Comment by dioramayuanito** [comment]
> @dioramayuanito - depending on your setup you may also want to load/configure [hls.worker.js](https://github.com/video-dev/hls.js/blob/46a7ca29bec3453bf39bc9919aba5ce189d17895/docs/API.md#workerpath)

are there any information should i know about hls.worker.js ? your previous hint about **var Hlsjs = require('hls.js/dist/hls.js');** is working successfully for my project 👌👍👍👍

**Comment by phloxic** [comment]
Sorry can't give you any qualified help in that regard. Pragmatically: I see a (non-fatal) Reference error in the console with my setup(s) which goes away when I specify the workerPath.

You are aware that from Video.js 7 and up HLS support is shipped with Video.js by default, and you might not need hls.js?
See:
https://videojs.com/blog/video-js-7-is-here/
and
https://github.com/videojs/http-streaming

**Comment by dioramayuanito** [comment]
> Sorry can't give you any qualified help in that regard. Pragmatically: I see a (non-fatal) Reference error in the console with my setup(s) which goes away when I specify the workerPath.
> 
> You are aware that from Video.js 7 and up HLS support is shipped with Video.js by default, and you might not need hls.js?
> See:
> https://videojs.com/blog/video-js-7-is-here/
> and
> https://github.com/videojs/http-streaming

Yes it is. You're right. I knew about hls.js vs vhs (videojs-http-streaming) things. I still use hls.js because JWPlayer uses it (is that right?). My player in https://20.detik.com can switch between hls.js and vhs.
I have a feeling that hls.js more robust than vhs (my 2 cents).
