### ISSUE TITLE
Captions do not appear to be available

### ISSUE THREAD

**Issue by newmaniese** [streamroot/videojs-hlsjs-plugin#16]
It appears that 608 captions that come in through HLS aren't being presented back to the video.js. These are supported from HLS.js.

**Comment by rkurbatov** [comment]
@newmaniese they are supported in 0.6.2 branch only (though with some problems). 0.5.x doesn't render them at all.

**Comment by tri170391** [comment]
Supported in the latest version of the plugin. 🎉
