### ISSUE TITLE
Dist script is needed

### ISSUE THREAD

**Issue by mkhazov** [streamroot/videojs-hlsjs-plugin#19]
Could you make a release, or add dist scripts to the repo? It would be really helpful for testing purposes.

**Comment by AxelDelmas** [comment]
We'll publish a dist on npm soon, right after cleaning up the build process.

**Comment by swordsreversed** [comment]
Is the npm publishing still happening?

**Comment by chrispappas** [comment]
Looked for this on NPM and no results, what's the status?

**Comment by ruslandinov** [comment]
Latest news -- we renamed the repo to avoid the confusion and started publishing to NPM, the package is here https://www.npmjs.com/package/videojs-hlsjs-plugin.
