### ISSUE TITLE
Subtitles inside m3u8 file are added to <video> element instead of Video.js text tracks

### ISSUE THREAD

**Issue by ghost** [streamroot/videojs-hlsjs-plugin#38]
I have a .m3u8 file with subtitles inside, such as [this one](https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8). The problem is that subtitles aren't shown on screen and the Video.js subtitles/captions buttons are hidden, but using the console you can see they are added into the &lt;video&gt; element.

    document.querySelector("video").textTracks; // returns a TextTrackList with the right TextTrack elements
    var player=videojs("video");
    player.textTracks().tracks_; // returns an empty array

Is this a bug or do I have to manually move the tracks from &lt;video&gt; to Video.js?

I'm using Video.js v5.18.4, Hls.js v0.7.6 and videojs5-hlsjs-source-handler v0.1.0

**Comment by tri170391** [comment]
It has been a while but just to let you know we added support of this feature in our latest version.
