### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by jviney** [streamroot/videojs-hlsjs-plugin#48]
Hi,

I'm seeing errors due the `error` variable not being defined here. Where is it supposed to come from?

https://github.com/streamroot/videojs5-hlsjs-source-handler/blob/master/lib/videojs5-hlsjs-source-handler.js#L70

Cheers,
-Jonathan.

**Comment by ruslandinov** [comment]
Thank you for your report @jviney , this is fixed now, closing the issue.
