### ISSUE TITLE
Not running if browser can handle HLS natively (i.e. Safari)

### ISSUE THREAD

**Issue by 13twelve** [streamroot/videojs-hlsjs-plugin#6]
Is it worth wrapping `attachVideojsStreamrootProvider(window, window.videojs);` in a test for if the browser can handle HLS natively?

```
if (!document.createElement('video').canPlayType('application/vnd.apple.mpegURL')) {
    attachVideojsStreamrootProvider(window, window.videojs);
}
```

I've noticed that Safari really struggles with HLS.js and so its probably worth letting it use its native support of HLS.

Pull request: https://github.com/streamroot/videojs-hls.js/pull/7

**Comment by darrennolan** [comment]
Is this required?  I haven't dug too deep - but looking at https://github.com/streamroot/videojs-hls.js/blob/master/lib/vjs-hls.js#L76 it appears that if hls.js reports unsupported - it won't run. As of the build I made today, iPhones are declared as 'not supported', and then from there videojs will use the native html player thereafter.
