### ISSUE TITLE
Cannot register source handler

### ISSUE THREAD

**Issue by stevendesu** [streamroot/videojs-hlsjs-plugin#89]
I have the following code that I'm processing with Webpack:

```js
import videojs from "video.js/core";
import hlsSourceHandler from "videojs-hlsjs-plugin";

hlsSourceHandler.register(videojs);
```

When I compile this code using Webpack and attempt to run the output `main.js`, I get the following error:

```
TypeError: videojs_hlsjs_plugin__WEBPACK_IMPORTED_MODULE_3___default.a.register is not a function
```

When I try `console.log`'ing the plugin:

```js
console.log(hlsSourceHandler):
```

all I see is an empty object:

```
Object { }
```

It seems like the exports may not be correct. I tried looking at the actual distributed file in my `node_modules` directory to understand, but there was just a single minified javascript file there. It wasn't very easy to make sense of it.

**Comment by tri170391** [comment]
Sorry, in a recent update of `Webpack` we kinda messed up the `webpack.config` exports. You can fix it by modifying the `output` section in `webpack.config` like this:

```javascript
...
output: {
      library: 'hlsSourceHandler', // Add these 2 lines
      libraryTarget: 'umd',
      path: distPath,
      filename: 'videojs-hlsjs-plugin.js'
    },
...
```

**Comment by tri170391** [comment]
Feel free to reopen if the issue happens again 😉

**Comment by kraiz** [comment]
Would be great if you publish this change to NPM.

**Comment by meikidd** [comment]
Would be great if you publish this change to NPM.
