### ISSUE TITLE
Upgrade HLS.js?

### ISSUE THREAD

**Issue by stevendesu** [streamroot/videojs-hlsjs-plugin#90]
HLS.js is now on `v0.12.4` which includes two hotfixes (including an important fix for Internet Explorer): https://github.com/video-dev/hls.js/releases

**Comment by tri170391** [comment]
Thank you, we are planning to bump the version of this dependency in the next release which should be today. 👍

**Comment by tri170391** [comment]
Update released with new Hls.js version 🎉
